# Generated by Django 5.2.17 on 2026-08-13 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_certificates_user_github_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notifications_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
