# Generated by Django 5.2.17 on 2026-08-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathonteam',
            name='hackathon_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='hackathonteam',
            name='max_members',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='hackathonteam',
            name='required_skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='teamrequest',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamrequest',
            name='hackathon_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='teamrequest',
            name='members_needed',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='teamrequest',
            name='project_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
