# Generated by Django 5.2.17 on 2026-08-13 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration', '0002_hackathonteam_hackathon_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='event_mode',
            field=models.CharField(default='Online', max_length=50),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='external_link',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='max_team_size',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='registration_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='status',
            field=models.CharField(default='OPEN', max_length=20),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='themes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
