# Generated by Django 5.2.17 on 2026-08-13 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration', '0003_hackathon_event_mode_hackathon_external_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='eligibility',
            field=models.CharField(default='Not specified', max_length=255),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='official_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='organizer',
            field=models.CharField(blank=True, default='Not specified', max_length=255),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='platforms',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='prize',
            field=models.CharField(default='Not specified', max_length=255),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='source_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='team_size_range',
            field=models.CharField(default='1-4', max_length=50),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='location',
            field=models.CharField(blank=True, default='Virtual', max_length=255),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='status',
            field=models.CharField(default='OPEN', max_length=255),
        ),
    ]
