# Generated by Django 5.2.17 on 2026-09-17 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration', '0004_hackathon_eligibility_hackathon_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamrequest',
            name='contact_method',
            field=models.CharField(blank=True, default='In-App Platform Application', max_length=255),
        ),
        migrations.AddField(
            model_name='teamrequest',
            name='hackathon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacancies', to='collaboration.hackathon'),
        ),
        migrations.AddField(
            model_name='teamrequest',
            name='required_role',
            field=models.CharField(blank=True, default='Other', max_length=255),
        ),
    ]
