# Generated by Django 5.2.17 on 2026-08-08 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_lecture_document_file_lecture_file_type_and_more'),
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicesession',
            name='lecture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_sessions', to='content.lecture'),
        ),
    ]
