# Generated by Django 5.2.17 on 2026-08-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='file_type',
            field=models.CharField(choices=[('AUDIO', 'Audio'), ('PDF', 'PDF'), ('PPTX', 'PPTX'), ('DOCX', 'DOCX')], default='AUDIO', max_length=10),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='lectures/'),
        ),
    ]
