# Generated by Django 5.2.17 on 2026-08-13 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='content.document'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='lecture',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='content.lecture'),
        ),
    ]
