# Generated by Django 5.2.17 on 2026-08-13 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_quiz_document_alter_quiz_lecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, default=''),
        ),
    ]
