# Generated by Django 5.2.17 on 2026-09-27 08:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_question_explanation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoubtSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic', models.CharField(default='General Doubt Session', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doubt_sessions', to='content.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doubt_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DoubtMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender', models.CharField(choices=[('STUDENT', 'Student'), ('AI', 'AI')], max_length=10)),
                ('text_content', models.TextField()),
                ('language', models.CharField(default='english', max_length=10)),
                ('retrieved_context', models.TextField(blank=True, default='')),
                ('context_found', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='content.doubtsession')),
            ],
        ),
    ]
