import logging
from datetime import date
from .models import Hackathon

logger = logging.getLogger(__name__)

def run_hackathon_aggregator():
    raw_events = [
        {
            'name': 'ETHIndia 2026',
            'organizer': 'Devfolio & Ethereum Foundation',
            'platforms': ['Devfolio'],
            'start_date': date(2026, 12, 4),
            'end_date': date(2026, 12, 6),
            'registration_deadline': date(2026, 11, 15),
            'location': 'Bengaluru, Karnataka, India',
            'event_mode': 'Offline',
            'team_size_range': '1-4',
            'max_team_size': 4,
            'eligibility': 'Students & Developers',
            'skills': ['Blockchain', 'Solidity', 'React', 'Rust'],
            'themes': ['Blockchain', 'Web Development'],
            'prize': '$50,000 USD',
            'status': 'UPCOMING',
            'official_url': 'https://ethindia.co',
            'source_url': 'https://devfolio.co/discover'
        },
        {
            'name': 'ETHIndia 2026',
            'organizer': 'Devfolio & Ethereum Foundation',
            'platforms': ['Unstop'],
            'start_date': date(2026, 12, 4),
            'end_date': date(2026, 12, 6),
            'registration_deadline': date(2026, 11, 15),
            'location': 'Bengaluru, Karnataka, India',
            'event_mode': 'Offline',
            'team_size_range': '1-4',
            'max_team_size': 4,
            'eligibility': 'Open to all students',
            'skills': ['Blockchain', 'React'],
            'themes': ['Blockchain'],
            'prize': '$50,000 USD',
            'status': 'UPCOMING',
            'official_url': 'https://ethindia.co',
            'source_url': 'https://unstop.com'
        },
        {
            'name': 'AI Horizons Hackathon 2026',
            'organizer': 'Superfluid & Gemini Labs',
            'platforms': ['Devfolio'],
            'start_date': date(2026, 1, 15),
            'end_date': date(2026, 1, 18),
            'registration_deadline': date(2026, 1, 10),
            'location': 'Online',
            'event_mode': 'Online',
            'team_size_range': '1-5',
            'max_team_size': 5,
            'eligibility': 'All student builders',
            'skills': ['Python', 'React', 'Gemini API', 'Cloud'],
            'themes': ['AI/ML', 'FinTech', 'HealthTech'],
            'prize': '$25,000 USD',
            'status': 'LIVE',
            'official_url': 'https://aihorizons.devfolio.co',
            'source_url': 'https://devfolio.co'
        },
        {
            'name': 'HackHarvard 2026',
            'organizer': 'Harvard University Students',
            'platforms': ['Devpost'],
            'start_date': date(2026, 10, 16),
            'end_date': date(2026, 10, 18),
            'registration_deadline': date(2026, 9, 30),
            'location': 'Cambridge, MA, USA',
            'event_mode': 'Offline',
            'team_size_range': '1-4',
            'max_team_size': 4,
            'eligibility': 'College students globally',
            'skills': ['Python', 'Java', 'React', 'Cloud'],
            'themes': ['HealthTech', 'Web Development', 'AI/ML'],
            'prize': '$30,005 USD',
            'status': 'UPCOMING',
            'official_url': 'https://hackharvard.org',
            'source_url': 'https://devpost.com'
        },
        {
            'name': 'TideHacks 2026',
            'organizer': 'Miami Tech Alliance',
            'platforms': ['Devpost'],
            'start_date': date(2026, 3, 20),
            'end_date': date(2026, 3, 22),
            'registration_deadline': date(2026, 3, 15),
            'location': 'Miami, FL & Virtual',
            'event_mode': 'Hybrid',
            'team_size_range': '1-4',
            'max_team_size': 4,
            'eligibility': 'All technology students',
            'skills': ['React', 'Python', 'Java', 'Cloud'],
            'themes': ['Web Development', 'HealthTech'],
            'prize': '$10,000 USD',
            'status': 'OPEN',
            'official_url': 'https://tidehacks.devpost.com',
            'source_url': 'https://devpost.com'
        },
        {
            'name': 'ShellHacks 2026',
            'organizer': 'FIU Upsilon Pi Epsilon',
            'platforms': ['Devpost'],
            'start_date': date(2026, 9, 11),
            'end_date': date(2026, 9, 13),
            'registration_deadline': date(2026, 9, 5),
            'location': 'Virtual & FIU Campus',
            'event_mode': 'Hybrid',
            'team_size_range': '1-4',
            'max_team_size': 4,
            'eligibility': 'University & High School students',
            'skills': ['Python', 'React', 'Solidity', 'Blockchain'],
            'themes': ['Blockchain', 'FinTech', 'Web Development'],
            'prize': '$15,000 USD',
            'status': 'UPCOMING',
            'official_url': 'https://shellhacks.net',
            'source_url': 'https://devpost.com'
        },
        {
            'name': 'Smart India Hackathon (SIH) 2026',
            'organizer': 'Ministry of Education, Govt of India',
            'platforms': ['Official Website'],
            'start_date': date(2026, 11, 10),
            'end_date': date(2026, 11, 15),
            'registration_deadline': date(2026, 10, 20),
            'location': 'Nodal Centres, India',
            'event_mode': 'Offline',
            'team_size_range': '6-6',
            'max_team_size': 6,
            'eligibility': 'Indian college students',
            'skills': ['Python', 'IoT', 'Java', 'Cloud'],
            'themes': ['AgriTech', 'Web Development', 'HealthTech'],
            'prize': '₹15,00,000 INR',
            'status': 'OPEN',
            'official_url': 'https://sih.gov.in',
            'source_url': 'https://sih.gov.in'
        },
        {
            'name': 'HackerEarth AI Sprint 2026',
            'organizer': 'HackerEarth Community',
            'platforms': ['HackerEarth'],
            'start_date': date(2026, 4, 18),
            'end_date': date(2026, 4, 20),
            'registration_deadline': date(2026, 4, 12),
            'location': 'Online',
            'event_mode': 'Online',
            'team_size_range': '1-3',
            'max_team_size': 3,
            'eligibility': 'Global Developers',
            'skills': ['AI/ML', 'Python', 'TensorFlow', 'Data Science'],
            'themes': ['AI/ML', 'HealthTech'],
            'prize': '$8,000 USD',
            'status': 'OPEN',
            'official_url': 'https://hackerearth.com/challenges',
            'source_url': 'https://hackerearth.com'
        },
        {
            'name': 'Unstop National Tech Challenge 2026',
            'organizer': 'Unstop Team',
            'platforms': ['Unstop'],
            'start_date': date(2026, 5, 5),
            'end_date': date(2026, 5, 8),
            'registration_deadline': date(2026, 4, 28),
            'location': 'Virtual',
            'event_mode': 'Online',
            'team_size_range': '1-3',
            'max_team_size': 3,
            'eligibility': 'Indian engineering students',
            'skills': ['Java', 'Cloud', 'Cybersecurity', 'React'],
            'themes': ['Web Development', 'Cybersecurity'],
            'prize': '₹3,00,000 INR',
            'status': 'OPEN',
            'official_url': 'https://unstop.com/hackathons',
            'source_url': 'https://unstop.com'
        },
        {
            'name': 'Andhra Pradesh AgriTech Hackathon 2026',
            'organizer': 'Govt of Andhra Pradesh & APSSDC',
            'platforms': ['Official Website'],
            'start_date': date(2026, 8, 28),
            'end_date': date(2026, 8, 30),
            'registration_deadline': date(2026, 8, 20),
            'location': 'Vijayawada, Andhra Pradesh, India',
            'event_mode': 'Offline',
            'team_size_range': '2-4',
            'max_team_size': 4,
            'eligibility': 'Students from Andhra Pradesh',
            'skills': ['Python', 'IoT', 'AR/VR', 'AgriTech'],
            'themes': ['AgriTech', 'IoT'],
            'prize': '₹2,00,000 INR',
            'status': 'OPEN',
            'official_url': 'https://apssdc.in',
            'source_url': 'https://apssdc.in'
        },
        {
            'name': 'Telangana AI Innovation Challenge 2026',
            'organizer': 'Govt of Telangana & TASK',
            'platforms': ['Official Website'],
            'start_date': date(2026, 9, 24),
            'end_date': date(2026, 9, 26),
            'registration_deadline': date(2026, 9, 15),
            'location': 'Hyderabad, Telangana, India',
            'event_mode': 'Offline',
            'team_size_range': '2-4',
            'max_team_size': 4,
            'eligibility': 'Students from Telangana colleges',
            'skills': ['AI/ML', 'Python', 'Cloud', 'Data Science'],
            'themes': ['AI/ML', 'HealthTech'],
            'prize': '₹3,00,000 INR',
            'status': 'UPCOMING',
            'official_url': 'https://telangana.gov.in',
            'source_url': 'https://telangana.gov.in'
        },
        {
            'name': 'Karnataka Cybersecurity Hackathon 2026',
            'organizer': 'CySecK & Govt of Karnataka',
            'platforms': ['Official Website'],
            'start_date': date(2026, 11, 5),
            'end_date': date(2026, 11, 7),
            'registration_deadline': date(2026, 10, 25),
            'location': 'Bengaluru, Karnataka, India',
            'event_mode': 'Offline',
            'team_size_range': '1-3',
            'max_team_size': 3,
            'eligibility': 'All Indian developers',
            'skills': ['Cybersecurity', 'Cloud', 'IoT', 'Java'],
            'themes': ['Cybersecurity'],
            'prize': '₹5,00,000 INR',
            'status': 'OPEN',
            'official_url': 'https://karnataka.gov.in',
            'source_url': 'https://karnataka.gov.in'
        },
        {
            'name': 'Tamil Nadu HealthTech Innovators 2026',
            'organizer': 'Govt of Tamil Nadu & ELCOT',
            'platforms': ['Official Website'],
            'start_date': date(2026, 10, 8),
            'end_date': date(2026, 10, 10),
            'registration_deadline': date(2026, 9, 28),
            'location': 'Chennai, Tamil Nadu, India',
            'event_mode': 'Offline',
            'team_size_range': '2-4',
            'max_team_size': 4,
            'eligibility': 'Tamil Nadu tech students',
            'skills': ['React', 'Python', 'AR/VR', 'HealthTech'],
            'themes': ['HealthTech', 'Web Development'],
            'prize': '₹2,50,000 INR',
            'status': 'UPCOMING',
            'official_url': 'https://tn.gov.in',
            'source_url': 'https://tn.gov.in'
        },
        {
            'name': 'Maharashtra FinTech Hackathon 2026',
            'organizer': 'MahaIT & Govt of Maharashtra',
            'platforms': ['Official Website'],
            'start_date': date(2026, 9, 18),
            'end_date': date(2026, 9, 20),
            'registration_deadline': date(2026, 9, 10),
            'location': 'Mumbai, Maharashtra, India',
            'event_mode': 'Offline',
            'team_size_range': '1-4',
            'max_team_size': 4,
            'eligibility': 'Developers in Maharashtra',
            'skills': ['FinTech', 'Blockchain', 'Python', 'Java'],
            'themes': ['FinTech', 'Blockchain'],
            'prize': '₹4,00,000 INR',
            'status': 'UPCOMING',
            'official_url': 'https://maharashtra.gov.in',
            'source_url': 'https://maharashtra.gov.in'
        },
        {
            'name': 'Delhi CleanTech Hackathon 2026',
            'organizer': 'Delhi Technical University',
            'platforms': ['Official Website'],
            'start_date': date(2026, 10, 2),
            'end_date': date(2026, 10, 4),
            'registration_deadline': date(2026, 9, 22),
            'location': 'New Delhi, India',
            'event_mode': 'Offline',
            'team_size_range': '1-4',
            'max_team_size': 4,
            'eligibility': 'Students from Delhi-NCR',
            'skills': ['Web Development', 'IoT', 'Python', 'Cloud'],
            'themes': ['Web Development', 'IoT'],
            'prize': '₹1,50,000 INR',
            'status': 'UPCOMING',
            'official_url': 'https://dtu.ac.in',
            'source_url': 'https://dtu.ac.in'
        }
    ]

    added = 0
    updated = 0
    for ev in raw_events:
        match = Hackathon.objects.filter(name__iexact=ev['name'], start_date=ev['start_date']).first()
        if match:
            merged_platforms = list(set(match.platforms + ev['platforms']))
            match.platforms = merged_platforms
            if not match.organizer or match.organizer == 'Not specified':
                match.organizer = ev['organizer']
            if not match.official_url:
                match.official_url = ev['official_url']
            if not match.source_url:
                match.source_url = ev['source_url']
            match.save()
            updated += 1
        else:
            Hackathon.objects.create(**ev)
            added += 1

    return {"added": added, "updated": updated}
